// Local Supabase connection details for the WP4 database test harness.
//
// SECURITY: the service-role key is read into memory only. It is never printed,
// never written to a file, and never placed in a VITE_* variable. Callers must
// keep it out of logs — see scripts/check-client-secrets.ts, which fails the
// build if the key name or value ever reaches browser-reachable code.
import { spawnSync } from "node:child_process";

export interface LocalSupabaseConfig {
  url: string;
  publishableKey: string;
  serviceRoleKey: string;
}

interface StatusJson {
  API_URL?: string;
  PUBLISHABLE_KEY?: string;
  ANON_KEY?: string;
  SERVICE_ROLE_KEY?: string;
  SECRET_KEY?: string;
}

/**
 * Resolve the local stack's URL and keys.
 *
 * Prefers environment variables (CI exports them after masking the secret), and
 * otherwise asks the locked Supabase CLI. Invoked via `<runtime> x supabase …`
 * with an args array and no shell, so a repository path containing spaces works
 * on Windows too (same convention as scripts/_supabase.ts).
 */
export function readLocalSupabaseConfig(): LocalSupabaseConfig {
  const fromEnv = {
    url: process.env.VITE_SUPABASE_URL,
    publishableKey: process.env.VITE_SUPABASE_PUBLISHABLE_KEY,
    serviceRoleKey: process.env.SUPABASE_SERVICE_ROLE_KEY,
  };
  if (fromEnv.url && fromEnv.publishableKey && fromEnv.serviceRoleKey) {
    return fromEnv as LocalSupabaseConfig;
  }

  const result = spawnSync(process.execPath, ["x", "supabase", "status", "-o", "json"], {
    encoding: "utf8",
    maxBuffer: 16 * 1024 * 1024,
  });
  if (result.status !== 0) {
    throw new Error(
      "could not read local Supabase status. Is the stack running (bun run supabase:start)?",
    );
  }

  let status: StatusJson;
  try {
    status = JSON.parse(result.stdout) as StatusJson;
  } catch {
    throw new Error("could not parse `supabase status -o json` output");
  }

  const url = fromEnv.url ?? status.API_URL;
  const publishableKey = fromEnv.publishableKey ?? status.PUBLISHABLE_KEY ?? status.ANON_KEY;
  const serviceRoleKey = fromEnv.serviceRoleKey ?? status.SERVICE_ROLE_KEY ?? status.SECRET_KEY;

  if (!url || !publishableKey || !serviceRoleKey) {
    // Deliberately does not echo any value it did find.
    throw new Error("local Supabase status did not provide a URL, publishable key and service key");
  }
  return { url, publishableKey, serviceRoleKey };
}

/**
 * The password used for every fixture Auth identity in a run. Generated by the
 * suite orchestrator and passed to child processes through the environment, so
 * no credential is ever committed to the repository.
 */
export function readFixturePassword(): string {
  const password = process.env.TORI_TEST_PASSWORD;
  if (!password) {
    throw new Error(
      "TORI_TEST_PASSWORD is not set. Run the whole suite with `bun run db:test:auth-suite`, " +
        "which generates a throwaway password for the run.",
    );
  }
  return password;
}
