/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransportRouteImport } from './routes/transport'
import { Route as TodayRouteImport } from './routes/today'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as ShoppingRouteImport } from './routes/shopping'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MoreRouteImport } from './routes/more'
import { Route as HouseholdRouteImport } from './routes/household'
import { Route as DesignSystemRouteImport } from './routes/design-system'
import { Route as ChildRouteImport } from './routes/child'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TemplatesIndexRouteImport } from './routes/templates.index'
import { Route as TasksIndexRouteImport } from './routes/tasks.index'
import { Route as FollowUpsIndexRouteImport } from './routes/follow-ups.index'
import { Route as TemplatesTrashRouteImport } from './routes/templates.trash'
import { Route as TemplatesTemplateIdRouteImport } from './routes/templates.$templateId'
import { Route as TasksUnassignedRouteImport } from './routes/tasks.unassigned'
import { Route as TasksTaskIdRouteImport } from './routes/tasks.$taskId'
import { Route as FollowUpsCaseIdRouteImport } from './routes/follow-ups.$caseId'

const TransportRoute = TransportRouteImport.update({
  id: '/transport',
  path: '/transport',
  getParentRoute: () => rootRouteImport,
} as any)
const TodayRoute = TodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const ShoppingRoute = ShoppingRouteImport.update({
  id: '/shopping',
  path: '/shopping',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MoreRoute = MoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => rootRouteImport,
} as any)
const HouseholdRoute = HouseholdRouteImport.update({
  id: '/household',
  path: '/household',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignSystemRoute = DesignSystemRouteImport.update({
  id: '/design-system',
  path: '/design-system',
  getParentRoute: () => rootRouteImport,
} as any)
const ChildRoute = ChildRouteImport.update({
  id: '/child',
  path: '/child',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesIndexRoute = TemplatesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TemplatesRoute,
} as any)
const TasksIndexRoute = TasksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TasksRoute,
} as any)
const FollowUpsIndexRoute = FollowUpsIndexRouteImport.update({
  id: '/follow-ups/',
  path: '/follow-ups/',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesTrashRoute = TemplatesTrashRouteImport.update({
  id: '/trash',
  path: '/trash',
  getParentRoute: () => TemplatesRoute,
} as any)
const TemplatesTemplateIdRoute = TemplatesTemplateIdRouteImport.update({
  id: '/$templateId',
  path: '/$templateId',
  getParentRoute: () => TemplatesRoute,
} as any)
const TasksUnassignedRoute = TasksUnassignedRouteImport.update({
  id: '/unassigned',
  path: '/unassigned',
  getParentRoute: () => TasksRoute,
} as any)
const TasksTaskIdRoute = TasksTaskIdRouteImport.update({
  id: '/$taskId',
  path: '/$taskId',
  getParentRoute: () => TasksRoute,
} as any)
const FollowUpsCaseIdRoute = FollowUpsCaseIdRouteImport.update({
  id: '/follow-ups/$caseId',
  path: '/follow-ups/$caseId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/child': typeof ChildRoute
  '/design-system': typeof DesignSystemRoute
  '/household': typeof HouseholdRoute
  '/more': typeof MoreRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/settings': typeof SettingsRoute
  '/shopping': typeof ShoppingRoute
  '/tasks': typeof TasksRouteWithChildren
  '/templates': typeof TemplatesRouteWithChildren
  '/today': typeof TodayRoute
  '/transport': typeof TransportRoute
  '/follow-ups/$caseId': typeof FollowUpsCaseIdRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/tasks/unassigned': typeof TasksUnassignedRoute
  '/templates/$templateId': typeof TemplatesTemplateIdRoute
  '/templates/trash': typeof TemplatesTrashRoute
  '/follow-ups/': typeof FollowUpsIndexRoute
  '/tasks/': typeof TasksIndexRoute
  '/templates/': typeof TemplatesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/child': typeof ChildRoute
  '/design-system': typeof DesignSystemRoute
  '/household': typeof HouseholdRoute
  '/more': typeof MoreRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/settings': typeof SettingsRoute
  '/shopping': typeof ShoppingRoute
  '/today': typeof TodayRoute
  '/transport': typeof TransportRoute
  '/follow-ups/$caseId': typeof FollowUpsCaseIdRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/tasks/unassigned': typeof TasksUnassignedRoute
  '/templates/$templateId': typeof TemplatesTemplateIdRoute
  '/templates/trash': typeof TemplatesTrashRoute
  '/follow-ups': typeof FollowUpsIndexRoute
  '/tasks': typeof TasksIndexRoute
  '/templates': typeof TemplatesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/child': typeof ChildRoute
  '/design-system': typeof DesignSystemRoute
  '/household': typeof HouseholdRoute
  '/more': typeof MoreRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/settings': typeof SettingsRoute
  '/shopping': typeof ShoppingRoute
  '/tasks': typeof TasksRouteWithChildren
  '/templates': typeof TemplatesRouteWithChildren
  '/today': typeof TodayRoute
  '/transport': typeof TransportRoute
  '/follow-ups/$caseId': typeof FollowUpsCaseIdRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/tasks/unassigned': typeof TasksUnassignedRoute
  '/templates/$templateId': typeof TemplatesTemplateIdRoute
  '/templates/trash': typeof TemplatesTrashRoute
  '/follow-ups/': typeof FollowUpsIndexRoute
  '/tasks/': typeof TasksIndexRoute
  '/templates/': typeof TemplatesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendar'
    | '/child'
    | '/design-system'
    | '/household'
    | '/more'
    | '/notifications'
    | '/onboarding'
    | '/settings'
    | '/shopping'
    | '/tasks'
    | '/templates'
    | '/today'
    | '/transport'
    | '/follow-ups/$caseId'
    | '/tasks/$taskId'
    | '/tasks/unassigned'
    | '/templates/$templateId'
    | '/templates/trash'
    | '/follow-ups/'
    | '/tasks/'
    | '/templates/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendar'
    | '/child'
    | '/design-system'
    | '/household'
    | '/more'
    | '/notifications'
    | '/onboarding'
    | '/settings'
    | '/shopping'
    | '/today'
    | '/transport'
    | '/follow-ups/$caseId'
    | '/tasks/$taskId'
    | '/tasks/unassigned'
    | '/templates/$templateId'
    | '/templates/trash'
    | '/follow-ups'
    | '/tasks'
    | '/templates'
  id:
    | '__root__'
    | '/'
    | '/calendar'
    | '/child'
    | '/design-system'
    | '/household'
    | '/more'
    | '/notifications'
    | '/onboarding'
    | '/settings'
    | '/shopping'
    | '/tasks'
    | '/templates'
    | '/today'
    | '/transport'
    | '/follow-ups/$caseId'
    | '/tasks/$taskId'
    | '/tasks/unassigned'
    | '/templates/$templateId'
    | '/templates/trash'
    | '/follow-ups/'
    | '/tasks/'
    | '/templates/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarRoute: typeof CalendarRoute
  ChildRoute: typeof ChildRoute
  DesignSystemRoute: typeof DesignSystemRoute
  HouseholdRoute: typeof HouseholdRoute
  MoreRoute: typeof MoreRoute
  NotificationsRoute: typeof NotificationsRoute
  OnboardingRoute: typeof OnboardingRoute
  SettingsRoute: typeof SettingsRoute
  ShoppingRoute: typeof ShoppingRoute
  TasksRoute: typeof TasksRouteWithChildren
  TemplatesRoute: typeof TemplatesRouteWithChildren
  TodayRoute: typeof TodayRoute
  TransportRoute: typeof TransportRoute
  FollowUpsCaseIdRoute: typeof FollowUpsCaseIdRoute
  FollowUpsIndexRoute: typeof FollowUpsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transport': {
      id: '/transport'
      path: '/transport'
      fullPath: '/transport'
      preLoaderRoute: typeof TransportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/today': {
      id: '/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof TodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shopping': {
      id: '/shopping'
      path: '/shopping'
      fullPath: '/shopping'
      preLoaderRoute: typeof ShoppingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/more': {
      id: '/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof MoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/household': {
      id: '/household'
      path: '/household'
      fullPath: '/household'
      preLoaderRoute: typeof HouseholdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-system': {
      id: '/design-system'
      path: '/design-system'
      fullPath: '/design-system'
      preLoaderRoute: typeof DesignSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/child': {
      id: '/child'
      path: '/child'
      fullPath: '/child'
      preLoaderRoute: typeof ChildRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/': {
      id: '/templates/'
      path: '/'
      fullPath: '/templates/'
      preLoaderRoute: typeof TemplatesIndexRouteImport
      parentRoute: typeof TemplatesRoute
    }
    '/tasks/': {
      id: '/tasks/'
      path: '/'
      fullPath: '/tasks/'
      preLoaderRoute: typeof TasksIndexRouteImport
      parentRoute: typeof TasksRoute
    }
    '/follow-ups/': {
      id: '/follow-ups/'
      path: '/follow-ups'
      fullPath: '/follow-ups/'
      preLoaderRoute: typeof FollowUpsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/trash': {
      id: '/templates/trash'
      path: '/trash'
      fullPath: '/templates/trash'
      preLoaderRoute: typeof TemplatesTrashRouteImport
      parentRoute: typeof TemplatesRoute
    }
    '/templates/$templateId': {
      id: '/templates/$templateId'
      path: '/$templateId'
      fullPath: '/templates/$templateId'
      preLoaderRoute: typeof TemplatesTemplateIdRouteImport
      parentRoute: typeof TemplatesRoute
    }
    '/tasks/unassigned': {
      id: '/tasks/unassigned'
      path: '/unassigned'
      fullPath: '/tasks/unassigned'
      preLoaderRoute: typeof TasksUnassignedRouteImport
      parentRoute: typeof TasksRoute
    }
    '/tasks/$taskId': {
      id: '/tasks/$taskId'
      path: '/$taskId'
      fullPath: '/tasks/$taskId'
      preLoaderRoute: typeof TasksTaskIdRouteImport
      parentRoute: typeof TasksRoute
    }
    '/follow-ups/$caseId': {
      id: '/follow-ups/$caseId'
      path: '/follow-ups/$caseId'
      fullPath: '/follow-ups/$caseId'
      preLoaderRoute: typeof FollowUpsCaseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface TasksRouteChildren {
  TasksTaskIdRoute: typeof TasksTaskIdRoute
  TasksUnassignedRoute: typeof TasksUnassignedRoute
  TasksIndexRoute: typeof TasksIndexRoute
}

const TasksRouteChildren: TasksRouteChildren = {
  TasksTaskIdRoute: TasksTaskIdRoute,
  TasksUnassignedRoute: TasksUnassignedRoute,
  TasksIndexRoute: TasksIndexRoute,
}

const TasksRouteWithChildren = TasksRoute._addFileChildren(TasksRouteChildren)

interface TemplatesRouteChildren {
  TemplatesTemplateIdRoute: typeof TemplatesTemplateIdRoute
  TemplatesTrashRoute: typeof TemplatesTrashRoute
  TemplatesIndexRoute: typeof TemplatesIndexRoute
}

const TemplatesRouteChildren: TemplatesRouteChildren = {
  TemplatesTemplateIdRoute: TemplatesTemplateIdRoute,
  TemplatesTrashRoute: TemplatesTrashRoute,
  TemplatesIndexRoute: TemplatesIndexRoute,
}

const TemplatesRouteWithChildren = TemplatesRoute._addFileChildren(
  TemplatesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarRoute: CalendarRoute,
  ChildRoute: ChildRoute,
  DesignSystemRoute: DesignSystemRoute,
  HouseholdRoute: HouseholdRoute,
  MoreRoute: MoreRoute,
  NotificationsRoute: NotificationsRoute,
  OnboardingRoute: OnboardingRoute,
  SettingsRoute: SettingsRoute,
  ShoppingRoute: ShoppingRoute,
  TasksRoute: TasksRouteWithChildren,
  TemplatesRoute: TemplatesRouteWithChildren,
  TodayRoute: TodayRoute,
  TransportRoute: TransportRoute,
  FollowUpsCaseIdRoute: FollowUpsCaseIdRoute,
  FollowUpsIndexRoute: FollowUpsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
