/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as HouseholdRouteImport } from './routes/household'
import { Route as ChildRouteImport } from './routes/child'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FollowUpsIndexRouteImport } from './routes/follow-ups.index'
import { Route as FollowUpsCaseIdRouteImport } from './routes/follow-ups.$caseId'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const HouseholdRoute = HouseholdRouteImport.update({
  id: '/household',
  path: '/household',
  getParentRoute: () => rootRouteImport,
} as any)
const ChildRoute = ChildRouteImport.update({
  id: '/child',
  path: '/child',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FollowUpsIndexRoute = FollowUpsIndexRouteImport.update({
  id: '/follow-ups/',
  path: '/follow-ups/',
  getParentRoute: () => rootRouteImport,
} as any)
const FollowUpsCaseIdRoute = FollowUpsCaseIdRouteImport.update({
  id: '/follow-ups/$caseId',
  path: '/follow-ups/$caseId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/child': typeof ChildRoute
  '/household': typeof HouseholdRoute
  '/onboarding': typeof OnboardingRoute
  '/follow-ups/$caseId': typeof FollowUpsCaseIdRoute
  '/follow-ups/': typeof FollowUpsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/child': typeof ChildRoute
  '/household': typeof HouseholdRoute
  '/onboarding': typeof OnboardingRoute
  '/follow-ups/$caseId': typeof FollowUpsCaseIdRoute
  '/follow-ups': typeof FollowUpsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/child': typeof ChildRoute
  '/household': typeof HouseholdRoute
  '/onboarding': typeof OnboardingRoute
  '/follow-ups/$caseId': typeof FollowUpsCaseIdRoute
  '/follow-ups/': typeof FollowUpsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/child'
    | '/household'
    | '/onboarding'
    | '/follow-ups/$caseId'
    | '/follow-ups/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/child'
    | '/household'
    | '/onboarding'
    | '/follow-ups/$caseId'
    | '/follow-ups'
  id:
    | '__root__'
    | '/'
    | '/child'
    | '/household'
    | '/onboarding'
    | '/follow-ups/$caseId'
    | '/follow-ups/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChildRoute: typeof ChildRoute
  HouseholdRoute: typeof HouseholdRoute
  OnboardingRoute: typeof OnboardingRoute
  FollowUpsCaseIdRoute: typeof FollowUpsCaseIdRoute
  FollowUpsIndexRoute: typeof FollowUpsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/household': {
      id: '/household'
      path: '/household'
      fullPath: '/household'
      preLoaderRoute: typeof HouseholdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/child': {
      id: '/child'
      path: '/child'
      fullPath: '/child'
      preLoaderRoute: typeof ChildRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/follow-ups/': {
      id: '/follow-ups/'
      path: '/follow-ups'
      fullPath: '/follow-ups/'
      preLoaderRoute: typeof FollowUpsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/follow-ups/$caseId': {
      id: '/follow-ups/$caseId'
      path: '/follow-ups/$caseId'
      fullPath: '/follow-ups/$caseId'
      preLoaderRoute: typeof FollowUpsCaseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChildRoute: ChildRoute,
  HouseholdRoute: HouseholdRoute,
  OnboardingRoute: OnboardingRoute,
  FollowUpsCaseIdRoute: FollowUpsCaseIdRoute,
  FollowUpsIndexRoute: FollowUpsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
