/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransportRouteImport } from './routes/transport'
import { Route as TodayRouteImport } from './routes/today'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as ShoppingRouteImport } from './routes/shopping'
import { Route as ShiftsRouteImport } from './routes/shifts'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MoreRouteImport } from './routes/more'
import { Route as HouseholdRouteImport } from './routes/household'
import { Route as ErrandsRouteImport } from './routes/errands'
import { Route as DesignSystemRouteImport } from './routes/design-system'
import { Route as ChildRouteImport } from './routes/child'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TransportIndexRouteImport } from './routes/transport.index'
import { Route as TemplatesIndexRouteImport } from './routes/templates.index'
import { Route as TasksIndexRouteImport } from './routes/tasks.index'
import { Route as ShoppingIndexRouteImport } from './routes/shopping.index'
import { Route as ShiftsIndexRouteImport } from './routes/shifts.index'
import { Route as NotificationsIndexRouteImport } from './routes/notifications.index'
import { Route as FollowUpsIndexRouteImport } from './routes/follow-ups.index'
import { Route as ErrandsIndexRouteImport } from './routes/errands.index'
import { Route as TransportUnassignedRouteImport } from './routes/transport.unassigned'
import { Route as TransportPendingRouteImport } from './routes/transport.pending'
import { Route as TransportNewRouteImport } from './routes/transport.new'
import { Route as TransportRideIdRouteImport } from './routes/transport.$rideId'
import { Route as TemplatesTrashRouteImport } from './routes/templates.trash'
import { Route as TemplatesTemplateIdRouteImport } from './routes/templates.$templateId'
import { Route as TasksUnassignedRouteImport } from './routes/tasks.unassigned'
import { Route as TasksTaskIdRouteImport } from './routes/tasks.$taskId'
import { Route as ShoppingListIdRouteImport } from './routes/shopping.$listId'
import { Route as ShiftsNewRouteImport } from './routes/shifts.new'
import { Route as ShiftsRuleIdRouteImport } from './routes/shifts.$ruleId'
import { Route as NotificationsPreferencesRouteImport } from './routes/notifications.preferences'
import { Route as FollowUpsCaseIdRouteImport } from './routes/follow-ups.$caseId'
import { Route as ErrandsErrandIdRouteImport } from './routes/errands.$errandId'
import { Route as TransportRideIdEditRouteImport } from './routes/transport.$rideId.edit'

const TransportRoute = TransportRouteImport.update({
  id: '/transport',
  path: '/transport',
  getParentRoute: () => rootRouteImport,
} as any)
const TodayRoute = TodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const ShoppingRoute = ShoppingRouteImport.update({
  id: '/shopping',
  path: '/shopping',
  getParentRoute: () => rootRouteImport,
} as any)
const ShiftsRoute = ShiftsRouteImport.update({
  id: '/shifts',
  path: '/shifts',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MoreRoute = MoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => rootRouteImport,
} as any)
const HouseholdRoute = HouseholdRouteImport.update({
  id: '/household',
  path: '/household',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrandsRoute = ErrandsRouteImport.update({
  id: '/errands',
  path: '/errands',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignSystemRoute = DesignSystemRouteImport.update({
  id: '/design-system',
  path: '/design-system',
  getParentRoute: () => rootRouteImport,
} as any)
const ChildRoute = ChildRouteImport.update({
  id: '/child',
  path: '/child',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TransportIndexRoute = TransportIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TransportRoute,
} as any)
const TemplatesIndexRoute = TemplatesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TemplatesRoute,
} as any)
const TasksIndexRoute = TasksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TasksRoute,
} as any)
const ShoppingIndexRoute = ShoppingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShoppingRoute,
} as any)
const ShiftsIndexRoute = ShiftsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShiftsRoute,
} as any)
const NotificationsIndexRoute = NotificationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NotificationsRoute,
} as any)
const FollowUpsIndexRoute = FollowUpsIndexRouteImport.update({
  id: '/follow-ups/',
  path: '/follow-ups/',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrandsIndexRoute = ErrandsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ErrandsRoute,
} as any)
const TransportUnassignedRoute = TransportUnassignedRouteImport.update({
  id: '/unassigned',
  path: '/unassigned',
  getParentRoute: () => TransportRoute,
} as any)
const TransportPendingRoute = TransportPendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => TransportRoute,
} as any)
const TransportNewRoute = TransportNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => TransportRoute,
} as any)
const TransportRideIdRoute = TransportRideIdRouteImport.update({
  id: '/$rideId',
  path: '/$rideId',
  getParentRoute: () => TransportRoute,
} as any)
const TemplatesTrashRoute = TemplatesTrashRouteImport.update({
  id: '/trash',
  path: '/trash',
  getParentRoute: () => TemplatesRoute,
} as any)
const TemplatesTemplateIdRoute = TemplatesTemplateIdRouteImport.update({
  id: '/$templateId',
  path: '/$templateId',
  getParentRoute: () => TemplatesRoute,
} as any)
const TasksUnassignedRoute = TasksUnassignedRouteImport.update({
  id: '/unassigned',
  path: '/unassigned',
  getParentRoute: () => TasksRoute,
} as any)
const TasksTaskIdRoute = TasksTaskIdRouteImport.update({
  id: '/$taskId',
  path: '/$taskId',
  getParentRoute: () => TasksRoute,
} as any)
const ShoppingListIdRoute = ShoppingListIdRouteImport.update({
  id: '/$listId',
  path: '/$listId',
  getParentRoute: () => ShoppingRoute,
} as any)
const ShiftsNewRoute = ShiftsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ShiftsRoute,
} as any)
const ShiftsRuleIdRoute = ShiftsRuleIdRouteImport.update({
  id: '/$ruleId',
  path: '/$ruleId',
  getParentRoute: () => ShiftsRoute,
} as any)
const NotificationsPreferencesRoute =
  NotificationsPreferencesRouteImport.update({
    id: '/preferences',
    path: '/preferences',
    getParentRoute: () => NotificationsRoute,
  } as any)
const FollowUpsCaseIdRoute = FollowUpsCaseIdRouteImport.update({
  id: '/follow-ups/$caseId',
  path: '/follow-ups/$caseId',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrandsErrandIdRoute = ErrandsErrandIdRouteImport.update({
  id: '/$errandId',
  path: '/$errandId',
  getParentRoute: () => ErrandsRoute,
} as any)
const TransportRideIdEditRoute = TransportRideIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => TransportRideIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/child': typeof ChildRoute
  '/design-system': typeof DesignSystemRoute
  '/errands': typeof ErrandsRouteWithChildren
  '/household': typeof HouseholdRoute
  '/more': typeof MoreRoute
  '/notifications': typeof NotificationsRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/settings': typeof SettingsRoute
  '/shifts': typeof ShiftsRouteWithChildren
  '/shopping': typeof ShoppingRouteWithChildren
  '/tasks': typeof TasksRouteWithChildren
  '/templates': typeof TemplatesRouteWithChildren
  '/today': typeof TodayRoute
  '/transport': typeof TransportRouteWithChildren
  '/errands/$errandId': typeof ErrandsErrandIdRoute
  '/follow-ups/$caseId': typeof FollowUpsCaseIdRoute
  '/notifications/preferences': typeof NotificationsPreferencesRoute
  '/shifts/$ruleId': typeof ShiftsRuleIdRoute
  '/shifts/new': typeof ShiftsNewRoute
  '/shopping/$listId': typeof ShoppingListIdRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/tasks/unassigned': typeof TasksUnassignedRoute
  '/templates/$templateId': typeof TemplatesTemplateIdRoute
  '/templates/trash': typeof TemplatesTrashRoute
  '/transport/$rideId': typeof TransportRideIdRouteWithChildren
  '/transport/new': typeof TransportNewRoute
  '/transport/pending': typeof TransportPendingRoute
  '/transport/unassigned': typeof TransportUnassignedRoute
  '/errands/': typeof ErrandsIndexRoute
  '/follow-ups/': typeof FollowUpsIndexRoute
  '/notifications/': typeof NotificationsIndexRoute
  '/shifts/': typeof ShiftsIndexRoute
  '/shopping/': typeof ShoppingIndexRoute
  '/tasks/': typeof TasksIndexRoute
  '/templates/': typeof TemplatesIndexRoute
  '/transport/': typeof TransportIndexRoute
  '/transport/$rideId/edit': typeof TransportRideIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/child': typeof ChildRoute
  '/design-system': typeof DesignSystemRoute
  '/household': typeof HouseholdRoute
  '/more': typeof MoreRoute
  '/onboarding': typeof OnboardingRoute
  '/settings': typeof SettingsRoute
  '/today': typeof TodayRoute
  '/errands/$errandId': typeof ErrandsErrandIdRoute
  '/follow-ups/$caseId': typeof FollowUpsCaseIdRoute
  '/notifications/preferences': typeof NotificationsPreferencesRoute
  '/shifts/$ruleId': typeof ShiftsRuleIdRoute
  '/shifts/new': typeof ShiftsNewRoute
  '/shopping/$listId': typeof ShoppingListIdRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/tasks/unassigned': typeof TasksUnassignedRoute
  '/templates/$templateId': typeof TemplatesTemplateIdRoute
  '/templates/trash': typeof TemplatesTrashRoute
  '/transport/$rideId': typeof TransportRideIdRouteWithChildren
  '/transport/new': typeof TransportNewRoute
  '/transport/pending': typeof TransportPendingRoute
  '/transport/unassigned': typeof TransportUnassignedRoute
  '/errands': typeof ErrandsIndexRoute
  '/follow-ups': typeof FollowUpsIndexRoute
  '/notifications': typeof NotificationsIndexRoute
  '/shifts': typeof ShiftsIndexRoute
  '/shopping': typeof ShoppingIndexRoute
  '/tasks': typeof TasksIndexRoute
  '/templates': typeof TemplatesIndexRoute
  '/transport': typeof TransportIndexRoute
  '/transport/$rideId/edit': typeof TransportRideIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/child': typeof ChildRoute
  '/design-system': typeof DesignSystemRoute
  '/errands': typeof ErrandsRouteWithChildren
  '/household': typeof HouseholdRoute
  '/more': typeof MoreRoute
  '/notifications': typeof NotificationsRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/settings': typeof SettingsRoute
  '/shifts': typeof ShiftsRouteWithChildren
  '/shopping': typeof ShoppingRouteWithChildren
  '/tasks': typeof TasksRouteWithChildren
  '/templates': typeof TemplatesRouteWithChildren
  '/today': typeof TodayRoute
  '/transport': typeof TransportRouteWithChildren
  '/errands/$errandId': typeof ErrandsErrandIdRoute
  '/follow-ups/$caseId': typeof FollowUpsCaseIdRoute
  '/notifications/preferences': typeof NotificationsPreferencesRoute
  '/shifts/$ruleId': typeof ShiftsRuleIdRoute
  '/shifts/new': typeof ShiftsNewRoute
  '/shopping/$listId': typeof ShoppingListIdRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/tasks/unassigned': typeof TasksUnassignedRoute
  '/templates/$templateId': typeof TemplatesTemplateIdRoute
  '/templates/trash': typeof TemplatesTrashRoute
  '/transport/$rideId': typeof TransportRideIdRouteWithChildren
  '/transport/new': typeof TransportNewRoute
  '/transport/pending': typeof TransportPendingRoute
  '/transport/unassigned': typeof TransportUnassignedRoute
  '/errands/': typeof ErrandsIndexRoute
  '/follow-ups/': typeof FollowUpsIndexRoute
  '/notifications/': typeof NotificationsIndexRoute
  '/shifts/': typeof ShiftsIndexRoute
  '/shopping/': typeof ShoppingIndexRoute
  '/tasks/': typeof TasksIndexRoute
  '/templates/': typeof TemplatesIndexRoute
  '/transport/': typeof TransportIndexRoute
  '/transport/$rideId/edit': typeof TransportRideIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendar'
    | '/child'
    | '/design-system'
    | '/errands'
    | '/household'
    | '/more'
    | '/notifications'
    | '/onboarding'
    | '/settings'
    | '/shifts'
    | '/shopping'
    | '/tasks'
    | '/templates'
    | '/today'
    | '/transport'
    | '/errands/$errandId'
    | '/follow-ups/$caseId'
    | '/notifications/preferences'
    | '/shifts/$ruleId'
    | '/shifts/new'
    | '/shopping/$listId'
    | '/tasks/$taskId'
    | '/tasks/unassigned'
    | '/templates/$templateId'
    | '/templates/trash'
    | '/transport/$rideId'
    | '/transport/new'
    | '/transport/pending'
    | '/transport/unassigned'
    | '/errands/'
    | '/follow-ups/'
    | '/notifications/'
    | '/shifts/'
    | '/shopping/'
    | '/tasks/'
    | '/templates/'
    | '/transport/'
    | '/transport/$rideId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendar'
    | '/child'
    | '/design-system'
    | '/household'
    | '/more'
    | '/onboarding'
    | '/settings'
    | '/today'
    | '/errands/$errandId'
    | '/follow-ups/$caseId'
    | '/notifications/preferences'
    | '/shifts/$ruleId'
    | '/shifts/new'
    | '/shopping/$listId'
    | '/tasks/$taskId'
    | '/tasks/unassigned'
    | '/templates/$templateId'
    | '/templates/trash'
    | '/transport/$rideId'
    | '/transport/new'
    | '/transport/pending'
    | '/transport/unassigned'
    | '/errands'
    | '/follow-ups'
    | '/notifications'
    | '/shifts'
    | '/shopping'
    | '/tasks'
    | '/templates'
    | '/transport'
    | '/transport/$rideId/edit'
  id:
    | '__root__'
    | '/'
    | '/calendar'
    | '/child'
    | '/design-system'
    | '/errands'
    | '/household'
    | '/more'
    | '/notifications'
    | '/onboarding'
    | '/settings'
    | '/shifts'
    | '/shopping'
    | '/tasks'
    | '/templates'
    | '/today'
    | '/transport'
    | '/errands/$errandId'
    | '/follow-ups/$caseId'
    | '/notifications/preferences'
    | '/shifts/$ruleId'
    | '/shifts/new'
    | '/shopping/$listId'
    | '/tasks/$taskId'
    | '/tasks/unassigned'
    | '/templates/$templateId'
    | '/templates/trash'
    | '/transport/$rideId'
    | '/transport/new'
    | '/transport/pending'
    | '/transport/unassigned'
    | '/errands/'
    | '/follow-ups/'
    | '/notifications/'
    | '/shifts/'
    | '/shopping/'
    | '/tasks/'
    | '/templates/'
    | '/transport/'
    | '/transport/$rideId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarRoute: typeof CalendarRoute
  ChildRoute: typeof ChildRoute
  DesignSystemRoute: typeof DesignSystemRoute
  ErrandsRoute: typeof ErrandsRouteWithChildren
  HouseholdRoute: typeof HouseholdRoute
  MoreRoute: typeof MoreRoute
  NotificationsRoute: typeof NotificationsRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  SettingsRoute: typeof SettingsRoute
  ShiftsRoute: typeof ShiftsRouteWithChildren
  ShoppingRoute: typeof ShoppingRouteWithChildren
  TasksRoute: typeof TasksRouteWithChildren
  TemplatesRoute: typeof TemplatesRouteWithChildren
  TodayRoute: typeof TodayRoute
  TransportRoute: typeof TransportRouteWithChildren
  FollowUpsCaseIdRoute: typeof FollowUpsCaseIdRoute
  FollowUpsIndexRoute: typeof FollowUpsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transport': {
      id: '/transport'
      path: '/transport'
      fullPath: '/transport'
      preLoaderRoute: typeof TransportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/today': {
      id: '/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof TodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shopping': {
      id: '/shopping'
      path: '/shopping'
      fullPath: '/shopping'
      preLoaderRoute: typeof ShoppingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shifts': {
      id: '/shifts'
      path: '/shifts'
      fullPath: '/shifts'
      preLoaderRoute: typeof ShiftsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/more': {
      id: '/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof MoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/household': {
      id: '/household'
      path: '/household'
      fullPath: '/household'
      preLoaderRoute: typeof HouseholdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/errands': {
      id: '/errands'
      path: '/errands'
      fullPath: '/errands'
      preLoaderRoute: typeof ErrandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-system': {
      id: '/design-system'
      path: '/design-system'
      fullPath: '/design-system'
      preLoaderRoute: typeof DesignSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/child': {
      id: '/child'
      path: '/child'
      fullPath: '/child'
      preLoaderRoute: typeof ChildRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transport/': {
      id: '/transport/'
      path: '/'
      fullPath: '/transport/'
      preLoaderRoute: typeof TransportIndexRouteImport
      parentRoute: typeof TransportRoute
    }
    '/templates/': {
      id: '/templates/'
      path: '/'
      fullPath: '/templates/'
      preLoaderRoute: typeof TemplatesIndexRouteImport
      parentRoute: typeof TemplatesRoute
    }
    '/tasks/': {
      id: '/tasks/'
      path: '/'
      fullPath: '/tasks/'
      preLoaderRoute: typeof TasksIndexRouteImport
      parentRoute: typeof TasksRoute
    }
    '/shopping/': {
      id: '/shopping/'
      path: '/'
      fullPath: '/shopping/'
      preLoaderRoute: typeof ShoppingIndexRouteImport
      parentRoute: typeof ShoppingRoute
    }
    '/shifts/': {
      id: '/shifts/'
      path: '/'
      fullPath: '/shifts/'
      preLoaderRoute: typeof ShiftsIndexRouteImport
      parentRoute: typeof ShiftsRoute
    }
    '/notifications/': {
      id: '/notifications/'
      path: '/'
      fullPath: '/notifications/'
      preLoaderRoute: typeof NotificationsIndexRouteImport
      parentRoute: typeof NotificationsRoute
    }
    '/follow-ups/': {
      id: '/follow-ups/'
      path: '/follow-ups'
      fullPath: '/follow-ups/'
      preLoaderRoute: typeof FollowUpsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/errands/': {
      id: '/errands/'
      path: '/'
      fullPath: '/errands/'
      preLoaderRoute: typeof ErrandsIndexRouteImport
      parentRoute: typeof ErrandsRoute
    }
    '/transport/unassigned': {
      id: '/transport/unassigned'
      path: '/unassigned'
      fullPath: '/transport/unassigned'
      preLoaderRoute: typeof TransportUnassignedRouteImport
      parentRoute: typeof TransportRoute
    }
    '/transport/pending': {
      id: '/transport/pending'
      path: '/pending'
      fullPath: '/transport/pending'
      preLoaderRoute: typeof TransportPendingRouteImport
      parentRoute: typeof TransportRoute
    }
    '/transport/new': {
      id: '/transport/new'
      path: '/new'
      fullPath: '/transport/new'
      preLoaderRoute: typeof TransportNewRouteImport
      parentRoute: typeof TransportRoute
    }
    '/transport/$rideId': {
      id: '/transport/$rideId'
      path: '/$rideId'
      fullPath: '/transport/$rideId'
      preLoaderRoute: typeof TransportRideIdRouteImport
      parentRoute: typeof TransportRoute
    }
    '/templates/trash': {
      id: '/templates/trash'
      path: '/trash'
      fullPath: '/templates/trash'
      preLoaderRoute: typeof TemplatesTrashRouteImport
      parentRoute: typeof TemplatesRoute
    }
    '/templates/$templateId': {
      id: '/templates/$templateId'
      path: '/$templateId'
      fullPath: '/templates/$templateId'
      preLoaderRoute: typeof TemplatesTemplateIdRouteImport
      parentRoute: typeof TemplatesRoute
    }
    '/tasks/unassigned': {
      id: '/tasks/unassigned'
      path: '/unassigned'
      fullPath: '/tasks/unassigned'
      preLoaderRoute: typeof TasksUnassignedRouteImport
      parentRoute: typeof TasksRoute
    }
    '/tasks/$taskId': {
      id: '/tasks/$taskId'
      path: '/$taskId'
      fullPath: '/tasks/$taskId'
      preLoaderRoute: typeof TasksTaskIdRouteImport
      parentRoute: typeof TasksRoute
    }
    '/shopping/$listId': {
      id: '/shopping/$listId'
      path: '/$listId'
      fullPath: '/shopping/$listId'
      preLoaderRoute: typeof ShoppingListIdRouteImport
      parentRoute: typeof ShoppingRoute
    }
    '/shifts/new': {
      id: '/shifts/new'
      path: '/new'
      fullPath: '/shifts/new'
      preLoaderRoute: typeof ShiftsNewRouteImport
      parentRoute: typeof ShiftsRoute
    }
    '/shifts/$ruleId': {
      id: '/shifts/$ruleId'
      path: '/$ruleId'
      fullPath: '/shifts/$ruleId'
      preLoaderRoute: typeof ShiftsRuleIdRouteImport
      parentRoute: typeof ShiftsRoute
    }
    '/notifications/preferences': {
      id: '/notifications/preferences'
      path: '/preferences'
      fullPath: '/notifications/preferences'
      preLoaderRoute: typeof NotificationsPreferencesRouteImport
      parentRoute: typeof NotificationsRoute
    }
    '/follow-ups/$caseId': {
      id: '/follow-ups/$caseId'
      path: '/follow-ups/$caseId'
      fullPath: '/follow-ups/$caseId'
      preLoaderRoute: typeof FollowUpsCaseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/errands/$errandId': {
      id: '/errands/$errandId'
      path: '/$errandId'
      fullPath: '/errands/$errandId'
      preLoaderRoute: typeof ErrandsErrandIdRouteImport
      parentRoute: typeof ErrandsRoute
    }
    '/transport/$rideId/edit': {
      id: '/transport/$rideId/edit'
      path: '/edit'
      fullPath: '/transport/$rideId/edit'
      preLoaderRoute: typeof TransportRideIdEditRouteImport
      parentRoute: typeof TransportRideIdRoute
    }
  }
}

interface ErrandsRouteChildren {
  ErrandsErrandIdRoute: typeof ErrandsErrandIdRoute
  ErrandsIndexRoute: typeof ErrandsIndexRoute
}

const ErrandsRouteChildren: ErrandsRouteChildren = {
  ErrandsErrandIdRoute: ErrandsErrandIdRoute,
  ErrandsIndexRoute: ErrandsIndexRoute,
}

const ErrandsRouteWithChildren =
  ErrandsRoute._addFileChildren(ErrandsRouteChildren)

interface NotificationsRouteChildren {
  NotificationsPreferencesRoute: typeof NotificationsPreferencesRoute
  NotificationsIndexRoute: typeof NotificationsIndexRoute
}

const NotificationsRouteChildren: NotificationsRouteChildren = {
  NotificationsPreferencesRoute: NotificationsPreferencesRoute,
  NotificationsIndexRoute: NotificationsIndexRoute,
}

const NotificationsRouteWithChildren = NotificationsRoute._addFileChildren(
  NotificationsRouteChildren,
)

interface ShiftsRouteChildren {
  ShiftsRuleIdRoute: typeof ShiftsRuleIdRoute
  ShiftsNewRoute: typeof ShiftsNewRoute
  ShiftsIndexRoute: typeof ShiftsIndexRoute
}

const ShiftsRouteChildren: ShiftsRouteChildren = {
  ShiftsRuleIdRoute: ShiftsRuleIdRoute,
  ShiftsNewRoute: ShiftsNewRoute,
  ShiftsIndexRoute: ShiftsIndexRoute,
}

const ShiftsRouteWithChildren =
  ShiftsRoute._addFileChildren(ShiftsRouteChildren)

interface ShoppingRouteChildren {
  ShoppingListIdRoute: typeof ShoppingListIdRoute
  ShoppingIndexRoute: typeof ShoppingIndexRoute
}

const ShoppingRouteChildren: ShoppingRouteChildren = {
  ShoppingListIdRoute: ShoppingListIdRoute,
  ShoppingIndexRoute: ShoppingIndexRoute,
}

const ShoppingRouteWithChildren = ShoppingRoute._addFileChildren(
  ShoppingRouteChildren,
)

interface TasksRouteChildren {
  TasksTaskIdRoute: typeof TasksTaskIdRoute
  TasksUnassignedRoute: typeof TasksUnassignedRoute
  TasksIndexRoute: typeof TasksIndexRoute
}

const TasksRouteChildren: TasksRouteChildren = {
  TasksTaskIdRoute: TasksTaskIdRoute,
  TasksUnassignedRoute: TasksUnassignedRoute,
  TasksIndexRoute: TasksIndexRoute,
}

const TasksRouteWithChildren = TasksRoute._addFileChildren(TasksRouteChildren)

interface TemplatesRouteChildren {
  TemplatesTemplateIdRoute: typeof TemplatesTemplateIdRoute
  TemplatesTrashRoute: typeof TemplatesTrashRoute
  TemplatesIndexRoute: typeof TemplatesIndexRoute
}

const TemplatesRouteChildren: TemplatesRouteChildren = {
  TemplatesTemplateIdRoute: TemplatesTemplateIdRoute,
  TemplatesTrashRoute: TemplatesTrashRoute,
  TemplatesIndexRoute: TemplatesIndexRoute,
}

const TemplatesRouteWithChildren = TemplatesRoute._addFileChildren(
  TemplatesRouteChildren,
)

interface TransportRideIdRouteChildren {
  TransportRideIdEditRoute: typeof TransportRideIdEditRoute
}

const TransportRideIdRouteChildren: TransportRideIdRouteChildren = {
  TransportRideIdEditRoute: TransportRideIdEditRoute,
}

const TransportRideIdRouteWithChildren = TransportRideIdRoute._addFileChildren(
  TransportRideIdRouteChildren,
)

interface TransportRouteChildren {
  TransportRideIdRoute: typeof TransportRideIdRouteWithChildren
  TransportNewRoute: typeof TransportNewRoute
  TransportPendingRoute: typeof TransportPendingRoute
  TransportUnassignedRoute: typeof TransportUnassignedRoute
  TransportIndexRoute: typeof TransportIndexRoute
}

const TransportRouteChildren: TransportRouteChildren = {
  TransportRideIdRoute: TransportRideIdRouteWithChildren,
  TransportNewRoute: TransportNewRoute,
  TransportPendingRoute: TransportPendingRoute,
  TransportUnassignedRoute: TransportUnassignedRoute,
  TransportIndexRoute: TransportIndexRoute,
}

const TransportRouteWithChildren = TransportRoute._addFileChildren(
  TransportRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarRoute: CalendarRoute,
  ChildRoute: ChildRoute,
  DesignSystemRoute: DesignSystemRoute,
  ErrandsRoute: ErrandsRouteWithChildren,
  HouseholdRoute: HouseholdRoute,
  MoreRoute: MoreRoute,
  NotificationsRoute: NotificationsRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  SettingsRoute: SettingsRoute,
  ShiftsRoute: ShiftsRouteWithChildren,
  ShoppingRoute: ShoppingRouteWithChildren,
  TasksRoute: TasksRouteWithChildren,
  TemplatesRoute: TemplatesRouteWithChildren,
  TodayRoute: TodayRoute,
  TransportRoute: TransportRouteWithChildren,
  FollowUpsCaseIdRoute: FollowUpsCaseIdRoute,
  FollowUpsIndexRoute: FollowUpsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
